### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:3000/movies 

### RECUPERAR PELICULA POR ID
GET http://localhost:3000/movies/eba69a27-1742-11ef-a566-046c59936623

### RECUPERAR PELICULA POR GENERO
GET http://localhost:3000/movies?genre=drama

### CREAR UNA PELICULA
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Goodather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://m.media-amazon.com/images/M/MV5BMTM2OTM3OTg1MF5BMl5BanBnXkFtZTcwMjg0OTkyMQ@@._V1_FMjpg_UX1000_.jpg",
  "genre": [
    "Crime",
    "Drama"
  ],
  "rate": 7.7
}

### ACTUALIZAR UNA PELICULA
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2023
}

### ELIMINAR UNA PELICULA
DELETE http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
